Release the Fabric Gov charts
greymatter-io/helm-charts pull request #780
Opened 2020-10-29 15:17 UTC by chrisbsmith

This PR should allow us to package the Fabric Gov chart.

2020-11-03 23:42 UTC, chrisbsmith commented
@moosecanswim  can I get a review here

2020-11-04 18:08 UTC, moosecanswim requested changes

2020-11-04 18:08 UTC, moosecanswim commented on .github/workflows/release.yaml
> +          sed -i.bak-gov -e "s|name: fabric|name: fabric-gov|" -e "s|Grey Matter Fabric|Grey Matter Fabric Gov|" fabric/Chart.yaml
does this work?  i dont see a place where you are creating a bak-gov file.  `sed -i` does inplace changes on the file so i think this should be `sed -i fabric/Chart.yaml`

2020-11-04 21:12 UTC, chrisbsmith commented on .github/workflows/release.yaml
> +          sed -i.bak-gov -e "s|name: fabric|name: fabric-gov|" -e "s|Grey Matter Fabric|Grey Matter Fabric Gov|" fabric/Chart.yaml
So, per the `sed` [man page](https://linux.die.net/man/1/sed), adding a suffex to `-i` creates a backup on the fly.  So the `sed` command actually creates `fabric/Chart.yaml.bak-gov`.  Though for this we don't really need a backup.

However, I did find that we were not changing the `jwt` chart to use the `jwt-gov` helm charts. So I did push an update that includes that.

2020-11-04 21:33 UTC, moosecanswim submitted a review, later dismissed

2020-11-04 22:09 UTC, moosecanswim approved these changes

2020-11-04 22:15 UTC, merged