Fix observables
greymatter-io/helm-charts pull request #815
Opened 2020-11-20 21:49 UTC by zoemccormick

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This PR addresses https://github.com/greymatter-io/helm-charts/issues/747. It fixes the current observables setup to correctly install and updates the README. Its not perfect but it at least works now and I think the instructions are more clear.

It also changes the prometheus-sa-role to a ClusterRole and creates a RoleBinding for each namespace in `global.control.additional_namespaces` to automatically give prom the right permissions.
<br/><br/>

2. What **changes to custom.yaml** are required?

None
<br/><br/>

3. Have you documented any additional setup steps or configurations options?

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

<br/><br/>

To test, do a normal install on this branch (need control version 1.5.1-dev for now because of [this bug]()).

Then go through the steps [here in the readme](https://github.com/greymatter-io/helm-charts/tree/fix_observables/observables#install-elk-stack).  You should be able to install observables without issues.

2020-11-23 14:47 UTC, chrisbsmith commented on observables/README.md
> +   Change the values for [`ELASTICSEARCH_HOST` and `KAFKA_BOOTSTRAP_SERVERS` here](./custom-values-files/logstash-values.yaml#L45) to `elasticsearch-master-headless.<OBSERVABLES-NAMESPACE>.svc` and `
Is it possible to get the namespace information from the make command and use it here, rather than asking the user to update the values file?

```
make observables OBSERVABLES_NAMESPACE=<OBSERVABLES-NAMESPACE>
```

2020-11-23 14:54 UTC, chrisbsmith commented on observables/README.md
> +5. [Configure the kibana proxy](#configure-the-kibana-proxy).
The next major bullet on in this readme is `## Configure the Kibana Proxy`, which is a duplicate of this.  Can we review the README one more time and make sure the steps are in the correct order?

2020-11-23 15:04 UTC, chrisbsmith requested changes
Overall these are great changes, but I think there's a few updates we need to make.  Let me know if you have any questions on my comments.

2020-11-23 15:04 UTC, chrisbsmith commented on observables/gm-config/kibana-observables-proxy/create.sh
> +greymatter create cluster < path-to-dir/00.cluster.json
The `path-to-dir` variable doesn't exist in the `create.sh` file. We should define this based on the output of the python script

2020-11-23 15:11 UTC, zoemccormick commented on observables/gm-config/kibana-observables-proxy-spire/create.sh
> +greymatter create cluster < path-to-dir/00.cluster.json
This value _is_ actually generated in the python script and replaced [here](https://github.com/greymatter-io/helm-charts/blob/82f2f7d0b0854ab8c27dde88fc278b6f94fa443f/observables/gm-config/json-builder.py#L95-L97) and the generated file will by in the directory gm-config/export/kibana-observables-proxy (this directory gm-config/kibana-observables-proxy holds the templates). This is really confusing - and I hope once I get a chance to look at pathogen and get it updated for the helm charts we can remove the python/gm-config directory all together and update the instructions to generate the configs using that.

2020-11-23 15:12 UTC, zoemccormick commented on observables/README.md
> +   Change the values for [`ELASTICSEARCH_HOST` and `KAFKA_BOOTSTRAP_SERVERS` here](./custom-values-files/logstash-values.yaml#L45) to `elasticsearch-master-headless.<OBSERVABLES-NAMESPACE>.svc` and `
good call, I didn't even consider this. its much cleaner now

2020-11-23 15:33 UTC, chrisbsmith reviewed
Thanks for the update @zoemccormick.  I'll get one of the SREs to run through this as well and then we'll get it merged.

2020-11-24 22:29 UTC, chrisbsmith approved these changes
LGTM

2020-11-24 22:40 UTC, merged