Upgrade elk
greymatter-io/helm-charts pull request #845
Opened 2021-01-08 20:53 UTC by zoemccormick

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Updates observables to the latest versions - for https://github.com/greymatter-io/greymatter/issues/427.

<br/><br/>

2. What **changes to custom.yaml** are required?

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Install observables stack as described in the observables/README.md - everything should behave as expected.
<br/><br/>

2021-01-08 21:00 UTC, chrisbsmith requested changes
@zoemccormick I have not fully reviewed this, but we need to hold on all PRs against the release-2.4 branch until we fully understand how we're going to manage the build artifacts. I think we just need to update our documentation for 1.3 to install a specific version of each artifact, but we need to verify. Merging this PR, and another others for 1.4 will cause the CI to build a new artifact, which will let anyone install 1.4 with a simple helm install greymatter without providing a version number.

2021-01-19 15:05 UTC, zoemccormick commented
@chrisbsmith with @moosecanswim's [updates last week to the docs](https://github.com/DecipherNow/gm-gitbook-sync/pull/381) I think this issue is resolved - let me know if I am ok to bring this out of draft? I suppose helm still will install the latest version if no version number is specified, but the commands now in the documentation will install the accurate version

2021-01-19 17:02 UTC, moosecanswim commented
@chrisbsmith @zoemccormick , All the contents of this PR are in the observables directory so git hub actions wont publish any grey matter charts anyway.  IMO this can be merged in without any issues to the helm install process for our charts.

2021-01-20 19:18 UTC, zoemccormick commented
ok I'm going to unWIP this one, I'll leave the spire upgrade for now

2021-01-21 17:06 UTC, dgoldstein1 approved these changes
looks great! tested and approved 🏁 

Just had one or two suggestions

2021-01-21 17:27 UTC, moosecanswim commented on observables/README.md
> +      "eventTopic": "greymatter",
This should be `observables` to allow the segmentation of observables.  otherwise it will be lumped in with all the core greymatter outputs in kibana

2021-01-21 17:32 UTC, zoemccormick commented on observables/README.md
> +      "eventTopic": "greymatter",
@moosecanswim  ahh thanks ok, this will require a couple of other changes - [here](https://github.com/greymatter-io/helm-charts/blob/3ff82000eaec698d658307b79bb596f9e1bd89ad/observables/Makefile#L129) (so actually [this](https://github.com/greymatter-io/helm-charts/blob/3ff82000eaec698d658307b79bb596f9e1bd89ad/observables/custom-values-files/logstash-values.yaml#L51)) and [here](https://github.com/greymatter-io/helm-charts/tree/upgrade_elk/observables#configure-kibana), does it makes sense to have everything in this setup be under `observables`? I'm not familiar with how we would actually want Kibana to be set up

2021-01-21 20:28 UTC, moosecanswim commented on observables/README.md
> +      "eventTopic": "greymatter",
oh im dumb.  i was reading this the wrong way.  however the event topic should be either the project or customer so we do not end up conflating statistics for multiple tennants together.

2021-01-25 15:35 UTC, dgoldstein1 approved these changes
Changes look good to me.

Did you want someone to run through the instructions again?

2021-01-25 15:40 UTC, moosecanswim approved these changes
LGTM

2021-01-25 15:41 UTC, merged

2021-02-23 16:44 UTC, zoemccormick commented
/pr release-2.3

2021-02-23 16:45 UTC, zoemccormick commented
\pr release-2.3