WIP: 841 control api config curl error
greymatter-io/helm-charts pull request #851
Opened 2021-01-13 18:02 UTC by dgoldstein1

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

<br/><br/>

2. What **changes to custom.yaml** are required?

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

<br/><br/>

2021-01-13 19:13 UTC, dontlaugh commented on fabric/control-api/templates/control-api-init-hook.yaml
> +          image: {{ .Values.global.waiter.image }}
Is this reference to "waiter" right?

2021-01-13 19:15 UTC, dontlaugh reviewed
Seems alright. I'll want SREs to look.

2021-01-13 19:15 UTC, dontlaugh commented on fabric/values.yaml
> +
```suggestion
```
Remove this extra line

2021-01-13 21:28 UTC, dgoldstein1 commented on fabric/control-api/templates/control-api-init-hook.yaml
> +          image: {{ .Values.global.waiter.image }}
I think so? Which waiter are you referring to?

2021-01-14 17:56 UTC, dontlaugh commented on fabric/control-api/templates/control-api-init-hook.yaml
> +          image: {{ .Values.global.waiter.image }}
I see now. I don't like that we have to spawn containers to block startup. But we will need to fix that in software.

This isn't a blocker from me to merge this PR :+1:

2021-01-14 17:57 UTC, dontlaugh approved these changes

2021-01-20 16:37 UTC, moosecanswim requested changes

2021-01-20 16:37 UTC, moosecanswim commented on global.yaml
> +  environment: openshift
@dgoldstein1 could you change this back to kubernetes (as a default)

2021-01-20 16:37 UTC, moosecanswim commented on global.yaml
> +  domain: greymatter.apps.rp.greymatter.services
could you also reset this to the default.

2021-01-20 17:32 UTC, dgoldstein1 commented
@moosecanswim thanks! I reset `global.yaml`

2021-01-21 20:07 UTC, moosecanswim approved these changes
Works as expected.  Tested on oc4.6 and k3d clusters

2021-01-21 21:27 UTC, merged