Update changes from release-2.3
greymatter-io/helm-charts pull request #867
Opened 2021-01-21 21:59 UTC by dgoldstein1

Adds in:

- https://github.com/greymatter-io/helm-charts/pull/851
- https://github.com/greymatter-io/helm-charts/pull/840

2021-02-02 19:37 UTC, zoemccormick approved these changes
Can't quite tell why this is failing in the lint and test charts - but when that's resolved and an SRE signs of on merging to `release-2.4` this looks good to me!

2021-02-03 01:52 UTC, dgoldstein1 commented
I think this is an issue with `release-2.4`. I created https://github.com/greymatter-io/helm-charts/issues/880 to track this

@moosecanswim can you review this? It should be update to date with `release-2.4`

2021-02-03 16:30 UTC, moosecanswim requested changes
there is an issue with the umberella chart testing action config which is in `.chart-testing/fabric-sense-data.yaml`

2021-02-03 16:30 UTC, moosecanswim commented on .chart-testing/fabric-sense-data.yaml
>  charts:
Could you change this file to read:
```
target-branch: release-2.4
chart-dirs:
  - .
```

To test this locally you can run ` ct lint --config .chart-testing/fabric-sense-data.yaml `

this is the ct [github](https://github.com/helm/chart-testing)

2021-02-03 16:33 UTC, chrisbsmith commented on .chart-testing/fabric-sense-data.yaml
>  charts:
Actually @dgoldstein1 , can you please make sure you rebase against `release-2.4` first? This file already exists in that branch with the changes @moosecanswim call out above . https://github.com/greymatter-io/helm-charts/blob/release-2.4/.chart-testing/fabric-sense-data.yaml

2021-02-03 16:34 UTC, moosecanswim commented
@dgoldstein1 that change is in release-2.4 so you might just want to rebase onto it

2021-02-03 19:36 UTC, moosecanswim commented
@dgoldstein1 i also just pushed an update to fabric and control-api charts so the version will need to be incremented again.

2021-02-03 21:13 UTC, dgoldstein1 commented on .chart-testing/fabric-sense-data.yaml
>  charts:
I get the same thing on release-2.4
```
 david@Davids-MacBook-Pro  ~/dev/work/helm-charts   release-2.4  ct lint --config .chart-testing/fabric-sense-data.yaml


Linting charts...
Version increment checking disabled.
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
Error: Error linting charts: Could not read 'Chart.yaml': open Chart.yaml: no such file or directory
Error linting charts: Could not read 'Chart.yaml': open Chart.yaml: no such file or directory
 ✘ david@Davids-MacBook-Pro  ~/dev/work/helm-charts   release-2.4  echo $?
1
```

2021-02-03 21:21 UTC, closed without merging

2021-02-03 21:23 UTC, dgoldstein1 commented
closing in favor of https://github.com/greymatter-io/helm-charts/pull/883. After rebasing needed to push a new branch which requires a new PR.

2021-02-03 21:25 UTC, chrisbsmith commented
`git push -f` 😄