Helm release names
greymatter-io/helm-charts pull request #888
Opened 2021-02-04 20:54 UTC by moosecanswim

updates the helm release names that the make files use.

to test install the mesh from the makefiles like normal `make secrets && make install`

do a helm ls

you will see a `*-dev`

This will help avoid the outage we had last week.

2021-02-04 21:05 UTC, chrisbsmith commented
@moosecanswim Rather than defining the name as `-dev`, what if we made a random string per deployment?  Something like `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1`.  (Though this doesn't work on a mac.)

2021-02-04 21:14 UTC, moosecanswim commented
@chrisbsmith we would need to set an environment value on the users comp so that we could reference it when its time to uninstall

2021-02-04 21:48 UTC, chrisbsmith commented
@moosecanswim or grab it from a `helm list`, or set a temp hidden file with the value.  just something to think about to try and randomize things.

2021-02-09 21:57 UTC, moosecanswim commented
@tilleryd , @chrisbsmith would like you to review this as well since it does have some user experience integration.

2021-02-09 21:58 UTC, moosecanswim commented
The origional issue from clickup 
```
Update the makefiles to change the release name from fabric`, `sense`, `edge`, `secrets`  to the form of fabric-<customer> default to fabric-dev .  This is will ensure that we do not accidentally destroy a production mesh if in a customers cluster and run make uninstall .
```

2021-02-16 15:07 UTC, chrisbsmith commented on edge/Makefile
> +CUST := $(shell cat ../global.yaml | docker run -i docker.greymatter.io/internal/yq:2.4.1 -r '.global.release.customer' )
I'm really on the fence about forcing this hard dependency on another docker image.  Can you explore another option using grep and/or sed or any other tool that could natively be on a machine?

2021-02-16 16:03 UTC, moosecanswim commented on edge/Makefile
> +CUST := $(shell cat ../global.yaml | docker run -i docker.greymatter.io/internal/yq:2.4.1 -r '.global.release.customer' )
the hard thing with yq and jq is they are easy to install and light but there are different versions.  The yq that works best is one that translates yaml to json then wraps json... we can use wither sed or awk but yq/jq are just so much cleaner (and will not be screwed up if we make changes to the global.yaml).

I chose docker because we can almost certainly guarantee that it will be on developers computers (and that docker image is hosted by us).

2021-02-22 18:34 UTC, moosecanswim commented
@chrisbsmith @tilleryd, Could i get a thumbs up or down?

2021-02-22 18:37 UTC, tilleryd commented on Makefile
> +lint-umberela-charts:
```suggestion
lint-umbrella-charts:
```

2021-02-22 18:37 UTC, tilleryd commented on Makefile
> +lint: lint-subcharts lint-edge-secrets lint-umberela-charts
```suggestion
lint: lint-subcharts lint-edge-secrets lint-umbrella-charts
```

2021-02-22 18:41 UTC, tilleryd commented on fabric/Makefile
> +NAME-FABRIC := fabric-$(CUST)-$(RAND)
Can these instructions be moved to a global function? The signature would take a chart name variable to be used in the customer name variable and value. Then you can replace the copy pasta with this function throughout.

2021-02-22 18:45 UTC, tilleryd requested changes
see comments

2021-02-23 14:50 UTC, tilleryd commented on global.yaml
>      # release.production: true will increase all (except control-api) replicas to the default_replicas.  Otherwise the default for each chart will be used
I'm going to comment on an unchanged line here. To me the term default here is overloaded and this comment doesn't clearly explain the difference between default_replicas and default.

2021-02-23 14:52 UTC, tilleryd commented on global.yaml
> +    customer: development
Can we use a better default customer name? `development` doesn't sound like a customer. Perhaps `greymatter`.

2021-02-23 14:59 UTC, tilleryd commented
I think the naming of the spire charts is strange.

```
spire-development-ir2msj-agent 
spire-development-ir2msj-server
```

I believe they should read:

```
spire-agent-development-ir2msj 
spire-server-development-ir2msj
```

2021-02-23 22:01 UTC, moosecanswim commented
@tilleryd I refactored the makefiles to reuse code in the `helpers.mk` file.  I also moved .PHONY to single lines

2021-02-24 01:57 UTC, moosecanswim commented
@chrisbsmith you can set the yq command in the `helpers.mk` file which is imported by each of the subchart makefiles

2021-02-24 14:56 UTC, tilleryd commented on global.yaml
> +    customer: greymatter-dev
@moosecanswim I am now thinking this should be an empty string by default. Since we use these charts in https://docs.greymatter.io/installation/installation-kubernetes and "customer" is very specific to operations, I think we should keep the default as is. Thus there will be no changes to our docs and the output will be the same as it has been for quickstart deployments and development.

2021-02-24 15:06 UTC, tilleryd commented
@moosecanswim I think a better implementation is to not create the `greymatter-mesh-identity-x` configmap if `production: true`. Currently, one would need to intentionally delete the configmap after install which still leaves the possibility for unintended deletion of the mesh.

2021-02-25 16:22 UTC, tilleryd commented on global.yaml
> +    customer: greymatter-dev
@moosecanswim thoughts?

2021-02-25 16:38 UTC, moosecanswim commented on global.yaml
> +    customer: greymatter-dev
I disagree with this.  The whole motivation behind this is to add an extra layer to prevent unintentional deletion of the mesh due to a dev using the wrong k8 context.  Lets say you are connected to a customer cluster but think you are connected to k3d.  if you run a `make uninstall` as it stands the makefile will uninstall the default releases `fabric` `sense` `edge` etc.  Since they are uninstalled there is no way to rollback or easily recover the mesh.

 This is what we think happened a couple weeks ago with the di2e mesh.

The way this pr protects against this is by ensuring that the release name is unique per installation/ customer.  This only really affects those using makefiles; customers deploying the mesh using our docs site will not be affected.  However this is laying the foundation for wrapping our helm charts in a go wrapper.  Using a wrapper with similar logic to the makefiles will allow us allow us to give these unintentional deletion protections to the customers.

The work that i did yesterday does automatically delete the configmap upon install.  This means that you will need to run a command to restore the `mesh-identity` configmap before running the uninstall.

2021-02-25 16:41 UTC, tilleryd commented on global.yaml
> +    customer: greymatter-dev
For production you need to have the value set as a standard operating procedure in my mind. You would change it anyways since `greymatter-dev` shouldn't be the default.

2021-02-25 16:48 UTC, tilleryd commented on global.yaml
> +    customer: greymatter-dev
@chrisbsmith thoughts? I don't want to be too pedantic and hold this up

2021-02-25 17:00 UTC, moosecanswim commented on global.yaml
> +    customer: greymatter-dev
If we leave it blank then there would still be a rand portion to the release.

2021-02-25 17:10 UTC, tilleryd commented on global.yaml
> +    customer: greymatter-dev
Ok, I'm probably splitting hairs here.

2021-02-25 17:11 UTC, tilleryd commented
@moosecanswim you just need to fix linting before I can approve

2021-02-25 21:41 UTC, tilleryd approved these changes
@moosecanswim 👍

2021-02-25 21:43 UTC, merged