WIP: Allow the helm charts to auto generate an edge ingress cert
greymatter-io/helm-charts pull request #919
Opened 2021-03-18 13:17 UTC by chrisbsmith

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Every year we go through a process of having to regenerate a user certificate when the current one expires. This PR allows the helm charts to auto generate an edge ingress cert and a user cert (stored in a k8s secrete) if `.Values.global.auto_generate_edge_certs` is set to `true`

The only downside here is that when using this method, a new P12 will need to be generated and loaded into the browser with every new GM deployment.

2. What **changes to global.yaml** are required?

Adding a new variable to the global section

3. Have you documented any additional setup steps or configurations options?

Yes, new steps are in the README

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

I haven't actually tested this yet.  Want to get it out there for thoughts before I go too far down this rabbit hole.

2021-03-18 13:24 UTC, chrisbsmith commented
This breaks the Helm Testing for now.  WIll need to update it to retrieve the new user cert

2021-03-18 13:43 UTC, dontlaugh commented on README.md
> +kubectl get secret greymatter-user-cert -o jsonpath="{.data['ca\.crt']}" > ca.crt
these don't need base64 decoding?

2021-03-18 13:43 UTC, dontlaugh commented on global.yaml
> +  # Generates random certs for edge ingress. Also generates a random user cert to enable ingress. If you have legitamite certificates you would like to use for ingress, those can be provided in secre
wrap these comments to 80-100

2021-03-18 13:44 UTC, dontlaugh commented on secrets/templates/_cert-helper.tpl
> +{{- end -}}
add a newline here

2021-03-18 13:50 UTC, chrisbsmith commented on README.md
> +kubectl get secret greymatter-user-cert -o jsonpath="{.data['ca\.crt']}" > ca.crt
thanks for the catch.  I haven't actually run these yet.

2021-03-18 13:51 UTC, chrisbsmith commented on global.yaml
> +  # Generates random certs for edge ingress. Also generates a random user cert to enable ingress. If you have legitamite certificates you would like to use for ingress, those can be provided in secre
:+1:

2021-03-18 13:51 UTC, chrisbsmith commented on secrets/templates/_cert-helper.tpl
> +{{- end -}}
:+1:

2021-03-18 14:08 UTC, tilleryd commented on README.md
> +By default, Grey Matter leverages mTLS communications for all traffic, including inbound traffic to the mesh. This means that a user is required to load a certificate into the browser to access Grey
```suggestion
By default, Grey Matter leverages mutual TLS (mTLS) communications for all traffic, including inbound traffic to the mesh. This means that all `https` requests must include TLS certificates whether that be via a web browser or RESTful client. The Grey Matter helm charts have the ability to generate random Ingress and User certificates to ensure unique certificates every time a cluster is launched. For web based authentication, these certificates can then be imported into a web browser, to access the mesh.
```

I thought this could use a bit of improvement.

2021-03-18 14:10 UTC, tilleryd commented on README.md
> +If you want to use the auto generated certs, you can set `.Values.global.auto_generate_edge_certs` to `true` and it will create a self-signed certificate for ingress and one for a user certificate.
```suggestion
If you want to use the auto generated certs, you can set `.Values.global.auto_generate_edge_certs` to `true` and it will create a self-signed certificate for Ingress and one for a User certificate.
```

Consistent casing with the previous paragraph.

2021-03-18 14:11 UTC, tilleryd commented on README.md
> +To get the user cert, run these commands:
```suggestion
To get the user certificate, run these commands:
```

Consistent long-hand.

2021-03-18 14:12 UTC, tilleryd commented on README.md
> +Then create a new P12 to load into your browser
```suggestion
Then create a new p12 certificate to load into your browser:
```

2021-03-18 14:22 UTC, justincely requested changes

2021-03-18 14:22 UTC, justincely commented on secrets/templates/_cert-helper.tpl
> +{{- printf "greymatter.user" -}}
The user_dn of the auto cert needs to be an entry in the users.json for jwt.  Without that, the user won't get a valid token when they come in.

2021-03-18 14:43 UTC, tilleryd commented on global.yaml
> +  auto_generate_edge_certs: true
I like that this is optional and defaults to true. It makes a lot of sense for someone coming using our public docs. I'll be setting this to false locally so I don't have to manage a bunch of different certs because in dev we (at least I do) install the mesh multiple times a week.

2021-03-18 14:47 UTC, tilleryd commented on global.yaml
> +  auto_generate_edge_certs: true
Can we pass a prop to `make install` that ultimately does `helm install ... --set=auto_generate_edge_certs=false`? That way, in dev we don't have to change global.yaml.

2021-03-18 17:34 UTC, chrisbsmith commented on global.yaml
> +  auto_generate_edge_certs: true
I can look into that, but what certs do you use if the quickstarts have expired?  B/c part of this PR, that I didn't do yet, will be to remove the certs/ folder

2021-03-18 18:23 UTC, tilleryd commented on global.yaml
> +  auto_generate_edge_certs: true
That sounds like a concern either way since there's no auto-cert-rotation. I'm referring to an option just for initial generation.

2021-03-18 19:33 UTC, chrisbsmith commented on secrets/templates/_cert-helper.tpl
> +{{- printf "greymatter.user" -}}
I believe I captured this.  When you have a minute can you verify?

2021-03-18 19:34 UTC, chrisbsmith commented on global.yaml
> +  auto_generate_edge_certs: true
I'm not sure I follow.  We should probably chat

2021-03-18 23:29 UTC, chrisbsmith commented on global.yaml
> +  auto_generate_edge_certs: true
@tilleryd I'd like to get this PR pushed through so we can get the cert capability out there.   I'll have to look into passing params to `make install`

2021-03-18 23:31 UTC, chrisbsmith commented
@dontlaugh @justincely @tilleryd , This PR is ready for one more review.  Some things to note:
* I quieted some of the Makefiles, hence the `@` in front of a few commands
* The CI/CD test passes again

2021-03-19 17:41 UTC, zakilur approved these changes
LGTM

2021-03-19 17:46 UTC, justincely approved these changes

2021-03-19 18:31 UTC, merged

2021-03-19 19:10 UTC, tilleryd commented on global.yaml
> +  auto_generate_edge_certs: true
No problem, it was more of a development heuristic.