Upgrade Catalog to 2.0 and bump versions
greymatter-io/helm-charts pull request #950
Opened 2021-05-13 18:57 UTC by bcmendoza

[ch-2576]

- Upgrades Catalog to 2.0 and replaces the catalog-init process with a configMap file that seeds data into Catalog on startup.
- Temporarily updates services cued for RCs to use development/latest (we can update after cutting RCs).

2021-06-21 17:14 UTC, dontlaugh commented
@zoemccormick Should we close this PR, do you think?

2021-06-21 17:18 UTC, zoemccormick commented
@dontlaugh I can update the versions once the GA releases are all cut

2021-06-22 18:21 UTC, chrisbsmith commented
The SREs are tracking this as PR that's going to drop 1.6 into place.  Is this a correct assumption?

2021-06-22 18:39 UTC, zoemccormick commented
yes @chrisbsmith

2021-06-24 15:57 UTC, chrisbsmith requested changes
Thanks for workings this update @bcmendoza . I do have a few comments that we need to address.

@moosecanswim and @zakilur  please make sure you get a review of this, especially the global cert usage on the edge.

2021-06-24 15:57 UTC, chrisbsmith commented on catalog.sh
> +#!/usr/bin/env bash
I don't think we want to check this file into the main branch.

2021-06-24 15:57 UTC, chrisbsmith commented on ci/scripts/gen-certs.sh
> +#!/bin/bash
I'm all for automation, but this script assume that the user has `acert` installed and in the path. If we keep it here, recommend adding a `command` check to see if it exists. Something like this will do

```
if ! command -v acert &> /dev/null
then
    echo "acert could not be found"
    exit
fi
```

2021-06-24 15:57 UTC, chrisbsmith commented on edge/templates/_edge_volumes.tpl
> +    {{- if .Values.global.global_certs.enabled }}
We need to review this because we allow for the users to specify a unique ingress cert.

https://github.com/greymatter-io/helm-charts/blob/b276c702444f2889554254201dedcf468776cd31/secrets/values.yaml#L1017

2021-06-24 15:57 UTC, chrisbsmith commented on edge/values.yaml
> +  global_certs:
I'm not 100% certain this is necessary since Edge is a unique case.

@moosecanswim  please review.

2021-06-24 15:57 UTC, chrisbsmith commented on fabric/jwt/values.yaml
> +        "label": "CN=istio-quickstart (Intermediate),OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US",
Is this really the name of the cert we want to publish?

2021-06-24 15:57 UTC, chrisbsmith commented on sense/catalog/templates/catalog.yaml
> -      initContainers:
I'm all about removing the complexity of init containers!

2021-06-24 15:57 UTC, chrisbsmith commented on sense/catalog/values.yaml
> +      value: 'true'
Let's make sure we turn this to `false` when we publish. We don't want to have our production services running at `debug` level.

2021-06-24 20:03 UTC, zoemccormick commented
@chrisbsmith this stuff was originally just meant to be used on the istio deployment when the quickstart certs expired - we can either try to clean these scripts up or include instructions on how to generate all of the certs and where to put them if we're worried about the global certs

2021-06-24 20:33 UTC, moosecanswim commented
@zoemccormick could yall clean up the scripts.  Adding more scripts just makes it harder to maintain customer environments.  If the cert is unique to the installation could it be generated with an init job?

2021-06-24 20:37 UTC, moosecanswim commented on global.yaml
> +        enabled: true
Using from file will not work for customers that do not have access to the helm charts source code.  At this time most customers do a `helm repo add greymatter <repo url>` then run a `helm install <x> greymatter/<chart>`.  With this as true the files will not exist so there will be an empty secret.

2021-06-24 22:07 UTC, chrisbsmith commented
@zoemccormick we we're under the impression this PR was making the move to 1.6. If that is not the case we need to start over, which tbh, may not be a bad thing. I'm not really sure of the state of the release-2.4 branch but I do know there are a ton of PRs that went into release-2.3 and not 2.4. 

We will need to define a better process for this. I'm debating moving everything to a "main" branch and then using tags to version control. I think this will prevent headache in the future and allow us to easily decouple the helm versions from GM version. 

@dontlaugh would love your input here as well. You have a solid understanding of this

2021-06-25 15:56 UTC, kaitmore commented
@chrisbsmith I do think that we should start over and I'm going to close this PR now. This branch is outdated and has a lot of our environment specific testing stuff. release-2.4 is also out of date so we should focus on getting that to parity with release-2.3 first. This PR can just serve as a reference for 1.6 changes.

2021-06-25 15:56 UTC, closed without merging

2021-06-25 15:57 UTC, chrisbsmith commented
@zakilur FYI