Add docker login to install section and reorganize
greymatter-io/helm-charts pull request #959
Opened 2021-06-02 17:44 UTC by ActualTrash

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This changes the documentation to include two missing steps in the installation process (logging into docker and generating certificates). It also reorganizes the documentation to make it (hopefully) easier to read and understand.

<br/><br/>

2. What **changes to custom.yaml** are required?

None

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

N/A

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

N/A

<br/><br/>

2021-06-02 19:42 UTC, chrisbsmith requested changes
minor comment to update how the k3d commands are laid out.  Overall, nice update.  Thanks!

2021-06-02 19:42 UTC, chrisbsmith commented on docs/Deploy with K3d.md
> +- Stop cluster `k3d cluster stop greymatter`
Can you add subsection or comment that these two lines are an alternative approach for starting k3d? It's a bit confusing to put them right under the two commands that make and then destroy the k3d cluster.  

You can do like you did before:
`There are several ways to create a k3d cluster...`

2021-06-02 19:54 UTC, ActualTrash commented on docs/Deploy with K3d.md
> +- Stop cluster `k3d cluster stop greymatter`
I was thinking of deleting lines 26 and 27 as they are repeated on lines 15 and 46 respectively. So that section would look like this:

### Stopping / Starting the cluster
These commands will stop or start the cluster without deleting or uninstalling greymatter.
- Stop cluster:`k3d cluster stop greymatter`
- Start cluster:
    - `k3d cluster start greymatter`
    - `export KUBECONFIG=$(k3d kubeconfig write greymatter)`
    - `kubectl config use-context k3d-greymatter`


I can either do this or add the comment, whichever would be less confusing.

2021-06-03 14:35 UTC, chrisbsmith commented on docs/Deploy with K3d.md
> +- Stop cluster `k3d cluster stop greymatter`
This look good to me, but I'll let you make the decision on what's less confusing. I'm more familiar with this so I have things ingrained in my head while you're new eyes on it.  So you will have a different opinion on the flow.

2021-06-03 16:26 UTC, chrisbsmith approved these changes
LGTM, thanks for the updates!

2021-06-03 16:48 UTC, merged