Helm docs
greymatter-io/helm-charts pull request #973
Opened 2021-07-28 20:54 UTC by moosecanswim

Update docs to point out only the most useful configurations.  This leverages helm-docs which is an opensource tool that replaces the gen docs python script.

2021-07-28 21:27 UTC, chrisbsmith commented
@moosecanswim is this something we can add to our github actions workflow? It's be awesome if we could automate the creation of this.

Or maybe we add it as a git commit hook?

2021-08-02 21:04 UTC, moosecanswim commented
@chrisbsmith Updated this so that it will build update the docs automatically if there is a change to a `values.yaml`, a readme template (`README.md.gotmpl`), `global.yaml`, or root `README.md`.

2021-08-03 13:22 UTC, chrisbsmith commented
@moosecanswim before merging, please squash these commits to clean the PR

2021-08-03 13:24 UTC, chrisbsmith commented on Makefile
> +generate-configs:
Can we call this `generate-documentation` instead?

2021-08-03 13:27 UTC, chrisbsmith requested changes
All around this is a really good PR and I'm glad you were able to get it into the automated workflow. I'd like to see you change the name from `-configs` to `-documentation` because that's what the workflow is actually doing for us.

2021-08-03 13:27 UTC, chrisbsmith commented on Makefile
> +update-global-configs:
Let's do a `s/configs/documentation/g` since we're actually updating documentation and not configurations.

2021-08-03 13:27 UTC, chrisbsmith commented on ci/helm-docs/global-configs.sh
> +#Can be yq if installed locally
I don't understand this comment.

2021-08-03 13:36 UTC, moosecanswim commented on Makefile
> +generate-configs:
Sure.

2021-08-03 13:38 UTC, moosecanswim commented on ci/helm-docs/global-configs.sh
> +#Can be yq if installed locally
```
#Can be yq if installed locally
YQCMD="docker run -i docker.greymatter.io/internal/yq:2.4.1"
```
I choose to use a docker image to make sure the version someone has installed locally will not mess anything up.  So `YQCMD` can either be `yq` or this docker run statement.

2021-08-03 13:52 UTC, moosecanswim commented
@chrisbsmith  updated per comments

2021-08-03 15:17 UTC, chrisbsmith commented on ci/helm-docs/global-configs.sh
> +#Can be yq if installed locally
OK, why don't you expand on the comment a little more so say ☝️ . For an external person, it may be a bit confusing

2021-08-03 15:25 UTC, moosecanswim commented on ci/helm-docs/global-configs.sh
> +#Can be yq if installed locally
Updated

2021-08-03 15:27 UTC, chrisbsmith submitted a review, later dismissed

2021-08-03 16:38 UTC, chrisbsmith approved these changes
LGTM

2021-08-03 16:41 UTC, merged