WIP gm 1.7 updates
greymatter-io/helm-charts pull request #981
Opened 2021-09-17 14:00 UTC by tilleryd

2021-09-22 19:51 UTC, chrisbsmith approved these changes
Everything launched as expected.  LGTM

2021-09-22 20:13 UTC, dontlaugh commented
Touch up the commit message when you squash :+1:

2021-09-23 11:45 UTC, bcmendoza requested changes
I loaded the app and am not seeing health checks enabled. When I checked the Catalog API for health check results, I only saw the main `discovery_controlplane_reports` one. Is configuring health checks something we're leaving up to the user to do at a later time?

2021-09-23 11:46 UTC, bcmendoza commented on sense/values.yaml
> +    version: 3.0.0-rc.1
```suggestion
    version: 3.0.0-rc.2
```

2021-09-23 11:46 UTC, bcmendoza commented on sense/catalog/Chart.yaml
> +appVersion: 3.0.0-rc.1
```suggestion
appVersion: 3.0.0-rc.2
```

2021-09-23 11:47 UTC, bcmendoza commented on sense/catalog/values.yaml
> +  version: 3.0.0-rc.1
```suggestion
  version: 3.0.0-rc.2
```

2021-09-23 11:47 UTC, bcmendoza commented on sense/catalog/values.yaml
> +    version: 3.0.0-rc.1
```suggestion
    version: 3.0.0-rc.2
```

2021-09-23 13:06 UTC, tilleryd commented
@bcmendoza I think there may be an issue with the health feature flag for the dashboard. It's supposed to be enabled by default for the release image. 

We should enable all health checks rather than require customers to do so. This feature is a first class citizen of the product and one of the primary features of the release. With that said, how do I turn them on?

2021-09-23 20:11 UTC, bcmendoza approved these changes
These changes look good. As discussed, Catalog needs a new RC to handle retries for connecting to Redis. I totally overlooked that in developing this feature.

2021-09-23 20:11 UTC, tilleryd commented
@bcmendoza All good. Thanks for looking into it.

2021-09-23 20:12 UTC, merged